spring:
  jpa: database-platform:org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://35.189.161.175:5432/hasura2?currentSchema=daniel
    username: postgres
    password: postgrespassword
    driverClassName: org.postgresql.Driver